#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="$(git rev-parse --git-dir)"
trap 'rm -f "$dir/$$.tags"' EXIT
{
    git ls-files --full-name;
    git --no-pager submodule --quiet foreach \
        'git ls-files --full-name | sed s!^!$path/!';
} | ctags --tag-relative -L - -f"$dir/$$.tags"
mv "$dir/$$.tags" "$dir/tags"
